-- CreateTable
CREATE TABLE `UseCase` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `businessUnit` VARCHAR(191) NULL,
    `businessOwner` VARCHAR(191) NULL,
    `vertical` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `assumptions` VARCHAR(191) NULL,
    `constraints` VARCHAR(191) NULL,
    `dependencies` VARCHAR(191) NULL,
    `crossDomainYesOrNo` ENUM('Yes', 'No') NOT NULL,
    `crossDomainValue` VARCHAR(191) NULL,
    `parentTheme` VARCHAR(191) NULL,
    `useCaseTheme` VARCHAR(191) NULL,
    `businessImpact` ENUM('Cost', 'Revenue', 'Both') NOT NULL,
    `businessImpactCostValue` VARCHAR(191) NULL,
    `businessImpactRevenueValue` VARCHAR(191) NULL,
    `impact` VARCHAR(191) NULL,
    `time` VARCHAR(191) NULL,
    `systemsInvolved` VARCHAR(191) NULL,
    `source` VARCHAR(191) NULL,
    `externalData` VARCHAR(191) NULL,
    `criticalDataElement` VARCHAR(191) NULL,
    `investmentCategory` VARCHAR(191) NULL,
    `competitiveThrust` VARCHAR(191) NULL,
    `dataTrust` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
